defaults: &defaults
   host: ds049858.mongolab.com
   port: 49858

development:
  <<: *defaults
  database: employee_development

test:
  <<: *defaults
  database: employee_test

# set these environment variables on your prod server
production:
 
  host: ds049858.mongolab.com
  port: 49858
  database: employee_development
  username: abin
  password: password007
